from pylooiengine import *
from pylooiengine.gui import *
import pylooiengine
import easygui
import world
from lift import Lift

class Launcher(LooiObject):
    def step(self):
        main_menu()
        self.deactivate()
Launcher()        

def kill_all():
    for l in main_window.unlayered_looi_objects:
        l.deactivate()
    for l in main_window.layered_looi_objects:
        l.deactivate()

def main_menu():
    kill_all()
    new = Button(800, 200, 400, 100, "New World", new_world, Color(.6,.6,.6), black, 64)
    new.button_depth = 10
    
    load = Button(800, 300, 400, 100, "Load", lambda:0, Color(.6,.6,.6), black, 64)
    load.button_depth = 10
    
    abort = Button(800, 400, 400, 100, "Quit", lambda:quit(), Color(.6,.6,.6), black, 64)
    abort.button_depth = 10

def new_world():
    kill_all()
    class NewWorldPrompt(LooiObject):
        def step(self):
            res = easygui.choicebox(msg="Would you like to start with a blank world or a world generated by topographic data?", choices=["Blank", "Data File"])
            if res == "Blank":
                res = easygui.multenterbox(fields=["Name", "Width", "Height"])
                the_world = world.new_world_from_dims(res[0], int(res[1]), int(res[2]))
                
                init_game_room(the_world)
            elif res == "Data File":
                res = easygui.multenterbox(fields=["Name", "Data File"])
                the_world = world.new_world_from_data_file(res[0], res[1],min_col=300)
                
                init_game_room(the_world)
                
            else:
                main_menu()
            self.deactivate()
    n = NewWorldPrompt()

def init_game_room(world):


    world.add_trees_elevation(1, 1,world.get_height()-1,world.get_width()-1)
    l = Lift(world)
    l.build([100,100,[x/100 for x in range(10,100,7)],100,300])
    world.activate()











